### ISSUE TITLE
webgpu报错

### ISSUE THREAD

**Issue by delta088** [xororz/web-realesrgan#4]
非常感谢build这个很好用的工具
我用docker部署后运行webgpu发现这个错误，请问需要如何解决呢

@tensorflow_tfjs.js?v=e34e8da5:2213 Uncaught (in promise) Error: Backend name 'webgpu' not found in registry
    at _Engine.setBackend (@tensorflow_tfjs.js?v=e34e8da5:2213:13)
    at Module.setBackend (@tensorflow_tfjs.js?v=e34e8da5:3364:17)
    at worker.js:17:18

**Comment by delta088** [comment]
了解 但是我是部署在本地直接用ip访问的
这个你在本地测试的时候是如何解决的呢

**Comment by xororz** [comment]
> 了解 但是我是部署在本地直接用ip访问的 这个你在本地测试的时候是如何解决的呢

本地测试我是用openssl自签了一个证书，webgpu这样的设计确实对本地开发来说有点麻烦了。
你也可以参考一下这个: https://developer.chrome.com/docs/web-platform/webgpu/troubleshooting-tips

**Comment by delta088** [comment]
搞定了 感谢，简单写了个dockerfile MacOS可用其他系统未测试

1.dockerfile

# 使用 Node.js 的官方镜像
FROM node:21.7.3

# 设置工作目录
WORKDIR /app

# 克隆 web-realesrgan 项目
RUN git clone https://github.com/xororz/web-realesrgan.git /app && ls -la /app

# 安装项目依赖
RUN npm install

# 安装 OpenSSL 并生成自签名证书
RUN apt-get update && apt-get install -y openssl && \
    mkdir -p /app/certs && \
    openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
    -keyout /app/certs/local.key -out /app/certs/local.crt \
    -subj "/CN=localhost"

# 暴露端口
EXPOSE 5173

# 将证书路径添加为环境变量，以便在配置文件中使用
ENV HTTPS=true
ENV SSL_CRT_FILE=/app/certs/local.crt
ENV SSL_KEY_FILE=/app/certs/local.key

# 启动 Web Real-ESRGAN 项目
CMD ["npm", "run", "dev"]

2. 修改vite.config.js内容为

import { fileURLToPath, URL } from "node:url";
import fs from "fs";
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
  server: {
    https:
      process.env.HTTPS === "true"
        ? {
            key: fs.readFileSync(process.env.SSL_KEY_FILE),
            cert: fs.readFileSync(process.env.SSL_CRT_FILE),
          }
        : false,
    port: 5173,
  },
});

3. run docker

real-esrgan-web % docker run -p 5173:5173 \
    -v /yourpath/realcugan:/app/realcugan \
    -v /yourpath/real-esrgan-web/realesrgan:/app/realesrgan \
    -v /yourpath/real-esrgan-web/vite.config.js:/app/vite.config.js \
    --restart unless-stopped \
    web-realesrgan
